dofile(LockOn_Options.script_path.."devices.lua")
dofile(LockOn_Options.script_path.."command_defs.lua")

local HUD_System = GetSelf()
local dev = GetSelf()
local sensor_data		= get_base_data()

local update_time_step = 0.01 --1/100
make_default_activity(update_time_step)

--local Parameter = get_param_handle("HUDBrightnessDown") //Test für später
--Parameter:set(0)

------------------------------------------------------------------FUNCTION-POST-INIT---------------------------------------------------------------------------------------------------
function post_initialize()
	
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	

end
------------------------------------------------------------------FUNCTION-SETCOMMAND---------------------------------------------------------------------------------------------------
function SetCommand(command,value)


end
------------------------------------------------------------------FUNCTION-UPDATE---------------------------------------------------------------------------------------------------
function update()
    --[[dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)
	dispatch_action(nil, 747)]]
	

	
	


end