local count = 0
local function counter()
	count = count + 1
	return count
end
-------DEVICE ID-------
devices                     = {}
devices["ELECTRIC_SYSTEM"]  = counter()
devices["ENGINE"]           = counter()
devices["FUEL"]             = counter()
devices["EXTLIGHTS"]        = counter()
devices["INTLIGHTS"]        = counter()
devices["ICEPROT"]          = counter()
devices["ENVIRON"]          = counter()
devices["GEAR"]             = counter()
devices["BRAKES"]           = counter()
devices["CMFD"]             = counter()
devices["DISPLAYCOMPUTER"]	= counter()
devices["CLOCK"]			= counter()
devices["AVIONICS"]         = counter()
devices["GUNSIGHT"]         = counter()
devices["AIRBRAKE"]         = counter()
devices["CANOPY"]           = counter()
devices["FLAPS"]            = counter()
devices["EXTANIM"]          = counter()
devices["WEAPON_SYSTEM"]    = counter()
devices["UFCP"]			    = counter()
devices["TEST"]             = counter()
devices["ALARM"]            = counter()
devices["HELMET_DEVICE"]    = counter()
devices["AUTOPILOT"]        = counter()
devices["WEAPONS"]          = counter()
devices["TACAN"]			= counter()
devices["VOR_ILS"]			= counter()
devices["NAV"]			    = counter()
devices["RADIO1"] 			= counter() 
devices["RADIO2"] 			= counter()
devices["COMM1"]		 	= counter()
devices["COMM2"]		 	= counter()
devices["INTERCOM"] 		= counter()
